config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #

  # Defines the root path route ("/")
  root 'events#index'
  resources :events
  resources :users
  resources :attendance, only: %i[create destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
# frozen_string_literal: true

class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  attr_accessor :event_name, :event_date

  belongs_to :creator, class_name: 'User'
  has_many :attendances
  has_many :attendees, through: :attendances, source: :user

  validates :name, presence: true, allow_blank: false, length: { minimum: 5, maximum: 50 }
  validates :date, presence: true, allow_blank: false
  validates :location, presence: true, allow_blank: false, length: { minimum: 5, maximum: 50 }



  validate do |event| 
    errors.add(:date, 'Event must be in the future') if event.date.present? && event.date < Date.today
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :nickname, uniqueness: true

  has_many :attendances
  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :attended_events, through: :attendances, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :email, :password, :current_password])
  end
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController

  def show_attended_events
    @attended_events = current_user.attended_events
  end

  def create
    Attendance.create(user_id: current_user.id, event_id: params[:event_id])
    flash[:notice] = 'You have successfully attended this event.'
    redirect_to event_path(params[:event_id])
  end

  def destroy
    Attendance.find_by(user_id: current_user.id, event_id: params[:event_id]).destroy
    flash[:notice] = 'You have successfully unattended this event.'
    redirect_to event_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      flash[:notice] = 'Event was successfully created'
      redirect_to @event
    else
      render 'new', status: :unprocessable_entity
    end
  end
  
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = 'Event was successfully deleted'
    redirect_to events_path
  end


  private

  def event_params
    params.require(:event).permit(:name, :date, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/attendance/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Attendance#index</h1>
  <p>Find me in app/views/attendance/index.html.erb</p>
</div>

app/views/attendance/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Attendance#show</h1>
  <p>Find me in app/views/attendance/show.html.erb</p>
</div>

app/views/events/index.html.erb
<% if current_user.present? %>
  <p>Welcome <%=current_user.nickname%>!</p>
<%end %>



<h1 class="my-10 max-w-full text-2xl"> Upcoming Events </h1>

<div class="flex flex-row flex-wrap">
  <% @events.each do |event| %>
    <% if event.date > Date.today %>
      <div class="m-2 p-6 bg-white rounded-lg border border-gray-200 shadow-md basis-[30%]">
        <div class="flex justify-between">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"> <%= event.name %> </h5>
          <% if event.creator == current_user %>
            <%= button_to "Delete", event_path(event) , method: :delete, class: "h-10 px-5 text-red-700 transition-colors duration-150 border border-red-500 rounded-lg focus:shadow-outline hover:bg-red-500 hover:text-red-100"  %>
          <% end %>
         </div> 
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"> <%= event.location%> </p>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"> <%= event.date%> </p>
        <%= link_to event_path(event) do %>
            <button class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-purple-500 rounded-lg hover:bg-purple-400 focus:ring-4 focus:outline-none focus:ring-purple-300">
           Event Details
          <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
            </button>
          <%end %>
      </div>
    <%end%>
  <%end%>
</div>


<h1 class="my-10 max-w-full text-2xl"> Past Events </h1>

<div class="flex flex-row flex-wrap">

  <% @events.each do |event| %>
    <% if event.date < Date.today %>
      <div class="m-2 p-6 bg-white rounded-lg border border-gray-200 shadow-md basis-[30%]">
        <div class="flex justify-between">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"> <%= event.name %> </h5>
          <% if event.creator == current_user %>
            <%= button_to "Delete", event_path(event) , method: :delete, class: "h-10 px-5 text-red-700 transition-colors duration-150 border border-red-500 rounded-lg focus:shadow-outline hover:bg-red-500 hover:text-red-100"  %>
          <% end %>
         </div> 
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"> <%= event.location%> </p>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"> <%= event.date%> </p>
        <%= link_to event_path(event) do %>
            <button class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-purple-500 rounded-lg hover:bg-purple-400 focus:ring-4 focus:outline-none focus:ring-purple-300">
           Event Details
          <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
            </button>
          <%end %>
      </div>
    <%end%>
  <%end%>
</div>

app/views/events/new.html.erb
<div class="flex flex-col">
    <div class="m-2 p-6 bg-white rounded-lg border border-gray-200 shadow-md basis-[30%] w-2/4 justify-center">

    <% if @event.errors.any? %>
        <% @event.errors.full_messages.each do |message|%>
         <h3 class="text-red-500"><%= message %></h3>
     <% end %>
    <% end %>

        <h2 class="text-2xl"> Create a new event </h2><br>
        <%= form_with method: :post, model: @event do |form| %>

            <%= form.text_field :name, placeholder: "Event Name", class: "block rounded-lg border border-grey-light w-full p-3 rounded mb-4" %> <br>

            <%= form.text_field :location, placeholder: "Event Location", class: "block rounded-lg border border-grey-light w-full p-3 rounded mb-4" %>

            <%= form.date_select :date, placeholder: "Event Date", class: "block rounded-lg border border-grey-light w-full p-3 rounded mb-4" %> 

            
            <%= form.submit "Create", class: "my-4 w-full text-center py-3 rounded bg-purple-500 text-white hover:bg-purple-400 focus:outline-none my-1 cursor-pointer"%>
            
        <% end %>
    </div>
</div>

app/views/events/show.html.erb
<div class="flex flex-col flex-wrap"> 
    <div class="m-2 p-6 bg-white rounded-lg border border-gray-200 shadow-md basis-[90%]">
      <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"> <%= @event.name %> </h5>
      <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"> <%= @event.location%> </p>
      <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"> <%= @event.date%> </p>
      <div> 
        <p> Created by <%= link_to @event.creator.nickname, user_path(@event.creator.id) %> </p>
        <div>
          <%if @event.attendees.size <=1%>
             <%= @event.attendees.size %> person is attending this event.
          <%else%>
            <%= @event.attendees.size %> people are attending this event.
          <%end%> <br>

          <% @event.attendees.each do |attendee| %>
            <%= link_to attendee.nickname, user_path(attendee.id), class: 'text-blue-600 font-bold hover:text-purple-400' %>, 
          <% end %>

        </div>  
      </div>

      <div>
        <% if user_signed_in? %>
          <% if @event.attendees.include?(current_user) %>
            <%= button_to "Leave Event", attendance_path(event_id: @event.id), method: :delete, class: 'text-center p-2 rounded bg-purple-500 text-white hover:bg-purple-400 focus:outline-none my-1' %>
          <%else%>
            <%=button_to "Join Event", attendance_index_path(event_id: @event.id), method: :post, class: 'text-center p-2 rounded bg-purple-500 text-white hover:bg-purple-400 focus:outline-none my-1' %>
          <%end%>
        <% end %>
      </div>
   </div> <br>

  <%= link_to "Back to Events", events_path, class: 'ml-3  hover:text-purple-400' %>

</div>







 

app/views/layouts/_navbar.html.erb
<nav class="flex flex-wrap items-center justify-between w-full py-4 md:py-0 px-4 text-lg text-gray-700 bg-white" >
    <div class="container mx-auto flex justify-between pt-5">

        <div class="logo flex my-3">
          <img class="" alt="Event Factory" width="42" height="30"  src="https://upload.wikimedia.org/wikipedia/commons/1/19/Factory_black.png">
          <button class="ml-1 py-2 font-sans font-semibold">
            <%= link_to "Event Factory", "/" %>
          </button>
        </div>

      <div class="hidden w-full md:flex md:items-center md:w-auto" id="menu">
        <ul class=" pt-4 text-base text-gray-700 md:flex md:justify-between md:pt-0">
          <% if !current_user %>
           <li>
             <button class="md:p-4 py-2 block hover:text-purple-400"> <%= link_to "Login", new_user_session_path %> </button>
           </li>
           <li>
             <button class="md:p-4 py-2 block hover:text-purple-400"> <%= link_to "Sign Up", new_user_registration_path %> </button>
           </li>
          <%end%>
          <% if user_signed_in? %>
            <li>
              <button class="md:p-4 py-2 block hover:text-purple-400"> <%= link_to "Create Event", new_event_path %> </button>
            </li>
            <li>
              <button class="md:p-4 py-2 block hover:text-purple-400"> <%= link_to "Profile", current_user %> </button>
            </li>
            <li>
              <button class="md:p-4 py-2 block hover:text-purple-400"> <%= link_to "Log out", destroy_user_session_path, :method => :delete %> </button>
            </li>
          <%end%>
        </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>

  </head>

  <body class="bg-slate-100">

    <%= render "layouts/navbar" %>

  <% unless notice.nil?%>
    <div class="clear-both p-4 mb-4 text-sm text-yellow-700 bg-yellow-100 rounded-lg dark:bg-yellow-200 dark:text-yellow-800" role="alert">
      <span class="font-medium"><%= notice %></span>
    </div>
  <% end %>

  <% unless alert.nil?%>
    <div class="p-4 mb-4 text-sm text-red-700 bg-red-100 rounded-lg dark:bg-red-200 dark:text-red-800" role="alert">
      <span class="font-medium"> <%= alert %> </span>
    </div>
  <% end %>

    
    <main class="container mx-auto mt-28">
      <%= yield %>
    </main>

  </body>
</html>

app/views/users/show.html.erb
<h3 class="text-xl"><%= @user.nickname %> Created</h3><br>


<div class="flex flex-row flex-wrap">
<%if @user.created_events.any?%>
  <% @user.created_events.each do |event| %>

     <div class="m-2 p-6 bg-white rounded-lg border border-gray-200 shadow-md basis-[30%]">
      <div class="flex justify-between">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"> <%= event.name %> </h5>
          <% if event.creator == current_user %>
            <%= button_to "Delete", event_path(event) , method: :delete, class: "h-10 px-5 text-red-700 transition-colors duration-150 border border-red-500 rounded-lg focus:shadow-outline hover:bg-red-500 hover:text-red-100"  %>
          <% end %>
         </div> 
      <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"> <%= event.location%> </p>
      <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"> <%= event.date%> </p>
      <%= link_to event_path(event) do %>
          <button class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-purple-500 rounded-lg hover:bg-purple-400 focus:ring-4 focus:outline-none focus:ring-purple-300">
         Event Details
        <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
          </button>
        <%end %>
    </div>
  <%end%>
<%else%>
  <p class="mb-5">No events created yet</p>
<%end%>
</div>



<h3 class="text-xl mt-8"><%= @user.nickname %> is Attending</h3>

<div class="flex flex-row flex-wrap mt-5">

<% if @user.attended_events.any? %>
 <% @user.attended_events.each do |event| %>
  <div class="m-2 p-6 bg-white rounded-lg border border-gray-200 shadow-md basis-[30%]">
    <div class="flex justify-between">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"> <%= event.name %> </h5>
          <% if event.creator == current_user %>
            <%= button_to "Delete", event_path(event) , method: :delete, class: "h-10 px-5 text-red-700 transition-colors duration-150 border border-red-500 rounded-lg focus:shadow-outline hover:bg-red-500 hover:text-red-100"  %>
          <% end %>
         </div> 
    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"> <%= event.location%> </p>
    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"> <%= event.date%> </p>
    <%= link_to event_path(event) do %>
      <button class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-purple-500 rounded-lg hover:bg-purple-400 focus:ring-4 focus:outline-none focus:ring-purple-300">
         Event Details
        <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
      </button>
    <% end %>
  </div>
  <% end %>
<% else %>
  <p> <%= @user.nickname %> is not attending any events </p>
<%end%>

</div>